name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.11.1.1165
      - run: ./cypress/cypress.sh
        shell: bash
